name: Python Unit Tests

# Controls when the workflow will run
on:
  # Triggers the workflow pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Sets up the Python environment
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Run tests with unittest
        run: |
          cd tests/
          python3 -m unittest discover -v



